"""Quick LLM test"""
import httpx

API_URL = "http://localhost:8000"

# Create session
r = httpx.post(f"{API_URL}/api/demo/sessions", timeout=10)
sid = r.json()["session_id"]
print(f"Session: {sid}")

# Answer questions
questions = [
    {"question_index": 1, "question_id": "q1_usage", "answer_key": "family"},
    {"question_index": 2, "question_id": "q2_priority", "answer_key": "safety"},
    {"question_index": 3, "question_id": "q3_load", "answer_key": "regret_anxiety"},
    {"question_index": 4, "question_id": "q4_style", "answer_key": "maximizer"},
    {"question_index": 5, "question_id": "q5_vehicle", "answer_key": "minivan"},
]

for q in questions:
    httpx.post(f"{API_URL}/api/demo/sessions/{sid}/answers", json=q, timeout=10)

# Get recommendation
rec = httpx.post(f"{API_URL}/api/demo/sessions/{sid}/recommend", timeout=10)
model = rec.json()["recommendations"][0]["model"]
print(f"Recommended: {model}")

# Get dealer talk
r2 = httpx.post(
    f"{API_URL}/api/demo/sessions/{sid}/dealer-talk",
    json={"top_model": model, "delegation_level": "co_pilot"},
    timeout=30,
)
data = r2.json()
print(f"\nGenerated by: {data['generated_by']}")
print(f"Talk length: {len(data['talk_script'])} chars")
print(f"\nTalk:\n{data['talk_script']}")
